### ISSUE TITLE
set a value to a field doesnt work

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#1]
If i set a value to a field this will not work.

`$username = new Input\Text('username');
        $username->setLabel('Username:')
              ->setValue('tester')
         ->setRequired(true)
         ->setAttribute('size', 40)
         ->addValidator(new Validator\AlphaNumeric());
        $form->addElement($username);`

i get the following output:
`<input type="text" name="username" id="username" value="" required="required" size="40" />`

is it my fault or is this an issue?

**Comment by nicksagona** [comment]
Yep - that's a bug. It should be setting the value and was failing to do so. I've patched it and pushed it up with the 2.0.0p3 release. Check it out and see if it's working for you now. Thanks for catching it.

**Comment by B0bbyD0llar** [comment]
thx for this fast response.

Unfortunately it doesnt work. Now i get an error.

`$aktion = new Input\Hidden('aktion');
$aktion->setValue("show");
$form->addElement($aktion);`

following error:

`Fatal error: Call to a member function setValue() on null`

**Comment by B0bbyD0llar** [comment]
Sry bro. There is no bug. It was my mistake. :-)
Now it works perfektly.
