### ISSUE TITLE
[Question] Missing setTemplate() in 3.x

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#10]
Hi,

i missing the setTemplate() Method in 3.x Version. Where is my fault?

Greetings

**Comment by nicksagona** [comment]
Check out bullet #4 on the changelog: https://github.com/popphp/pop-form/blob/master/CHANGELOG.md

All of the v2 template stuff was removed b/c it was really just a duplication of what's under the pop-view component. So now, you can use the pop-view component and use the prepareForView() method to pass the form object onto a view object to be rendered.

Let me know if that makes sense. Thanks.

**Comment by B0bbyD0llar** [comment]
i will try. thanks.
