### ISSUE TITLE
[BUG] label attribute has no effect

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#11]
Hi,

if you use setRequired(true) addition atrributes to label are ignored.
Example:

`$batitel = new Input\Text('batitel');
$batitel
            ->setLabel('Bezeichnung')
            ->setLabelAttribute("class", "col-md-2 control-label")
            ->setAttribute('placeholder', 'Bezeichnung angeben')
            ->setAttribute('class', "form-control")
            ->setRequired(true)
            ->setHint('Die Bezeichnung sollte kurz aber Aussagekräftig sein.');
        $form->addField($batitel);`

**Comment by nicksagona** [comment]
Ok, this has been patched and released under v3.1.1

**Comment by B0bbyD0llar** [comment]
Hi,

 i have testet. in my opinion it would be better if the "required" class additionaly added to the element.
