### ISSUE TITLE
[BUG] after setFieldValues($_POST) submit button text disappears

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#12]
after i use the method setFieldValues($_POST) the "nodeValue" from the submit button is empty.

**Comment by nicksagona** [comment]
Are you using an Input\Submit element or a Button element?

**Comment by B0bbyD0llar** [comment]
i use the button element.

`$submit = new Pop\Form\Element\Button('submit', $saveButtonText);
        $submit->setAttribute("class", "btn btn-primary");
        $form->addField($submit);`

**Comment by nicksagona** [comment]
Ok, this has been patched and released under v3.1.1
