### ISSUE TITLE
[ENHANCEMENT] combinded errors for the whole form

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#13]
for a better use in templates it would be helpful if errors serve in an additionally array.

**Comment by nicksagona** [comment]
That already exists. You can use $form->getAllErrors() to get an array of all form errors. Or, you can use $form->getErrors('fieldname') to get just the errors of a specific field. Let me know if that works for you.

**Comment by B0bbyD0llar** [comment]
Great. Thanks.
