### ISSUE TITLE
[Question] Is there an example for radio

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#15]
Hello,

is there an example for the optimal use of radio-buttons and radiosets?

**Comment by B0bbyD0llar** [comment]
and is there a way to deal with bootstarp style like:

```html
<label>
    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
    Option one is this and that&mdash;be sure to include why it's great
  </label>```

**Comment by nicksagona** [comment]
If you're referring to having the input element inside of the label element, that's not possible, nor is it semantically correct. You can have the label render after the input element and do different things regarding that, but pop-form won't render the input element inside of the label element.

If you want more control with placement of the labels and elements using pop-form, then I would recommend using the form element objects themselves (and not the array field configs.) That would give you the greatest amount of control over placement of labels and elements.

http://docs.popphp.org/en/latest/user_guide/forms.html

In Bootstrap's docs, they only show examples with labels rendering after the input element (never is the input element inside the label element.)
https://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios

**Comment by nicksagona** [comment]
Closing as it's been addressed.
