### ISSUE TITLE
[Q] Validate form field against other

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#18]
Hello,

short question. Is it possible to validate an form field against an other?

**Comment by nicksagona** [comment]
Yep - you sure can. You assign the validator(s) after a POST submission and on whatever conditions require the validation. A common example would be checking to make sure the `password2` field matches the `password1` field, right? So for example, I might have a form class like `MyApp\Form\User` that extends `Pop\Form\Form` and have this method in it:

```
public function setFieldValues(array $values = null)
{
    parent::setFieldValues($values);

    if (($_POST) && !empty($this->password1)) {
        $this->getField('password2')
             ->setRequired(true)
             ->addValidator(
                  new Validator\Equal($this->password1, 'The passwords do not match.')
             );
    }
}
```

**Comment by B0bbyD0llar** [comment]
Thanks. Thats not exacly this what i looking for but i will try to solve my problem.
