### ISSUE TITLE
[Q] Checkbox via Config & set Checkboxvalue

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#19]
Hi,

first question:
Is it possible to setup a checkbox via config?
```php
$formConfig = [
            'test' => [
                'type' => 'checkbox',
                'value' => 'testvalue',
                'label' => 'This is a Test'
            ],
        ];

$form = Form::createFromConfig($formConfig);
```
this results in an CheckboxSet, but i want a simple checkbox. Is there a way to config a simple checkbox?

second question:

i want to set a value to a checkbox, but i dont want to "check" this checkbox. So i tried:

```php
        $test= new Checkbox('test','testvalue_if_checked');
        $test->setAttribute('class','custom-control-input');
        $test->setLabel('Test');
        $test->setLabelAttribute('class','col-form-label');
        $test->addField($test);
```

how can i do it right?

**Comment by nicksagona** [comment]
Currently this isn't possible, but I'll look into it. (Sorry for the delayed response - been a busy past month.)

**Comment by nicksagona** [comment]
Ok so check out the new release I just pushed up 3.4.0. So now `checkbox` and `checkbox-set` as well as `radio` and `radio-set` are treated differently with the field configs. The `checkbox` and `radio` will create a simple, single field and `checkbox-set` and `radio-set` will function as before. I believe it's better separation and definition, but unfortunately will come with a little backward compatibility issues for anyone using `checkbox` or `radio` and expecting the fieldsets.

**Comment by nicksagona** [comment]
As for your second request, that can be done, either via config or programmatically, like this:
(Config)
```php
$fields = [
    'colors' => [
        'type'  => 'checkbox-set',
        'label' => 'Colors',
        'values' => [
            'Red', 'Blue', 'Green'
        ],
        'checked' => ['Red', 'Green'] // This will make the 'Red' and 'Green' checkboxes default to checked
    ]
    'cars' => [
        'type'  => 'radio-set',
        'label' => 'Cars',
        'values' => [
            'Truck', 'Sedan', 'SUV'
        ],
        'checked' => 'Truck' // This will make the 'Truck' radio default to checked
    ]
];
```
(Or single config)

```php
$fields = [
    'colors' => [
        'type'    => 'checkbox',
        'label'   => 'Color',
        'value'   => 'Red',
        'checked' => true // This will make the single 'Red' checkbox default to checked
    ]
    'cars' => [
        'type'    => 'radio',
        'label'   => 'Car',
        'value'   => 'Truck',
        'checked' => true // This will make the 'Truck' radio default to checked
    ]
];

```

(Programmatically)

```php
$checkbox = new Input\Checkbox('colors', 'Red');
$checkbox->check(); // This will make the single 'Red' checkbox default to checked

$radio = new Input\Radio('cars', 'Truck');
$radio->check(); // This will make the single 'Truck' radio default to checked
```

**Comment by B0bbyD0llar** [comment]
Thanks a lot. I will try it.

**Comment by B0bbyD0llar** [comment]
I have noticed that the checkbox is always activated. Even if I set "checked" to false. Is that only the case with me?

**Comment by nicksagona** [comment]
Are you talking about in the DOM?

**Comment by B0bbyD0llar** [comment]
Yes

**Comment by nicksagona** [comment]
I'd have to see a code sample to see exactly what you're talking about, but when I run the code in this gist, the DOM behaves as expected. The checkboxes "checked" property correctly changes as I click the links with the functions on them:

https://gist.github.com/nicksagona/6fa3b7ecc3276c52053e8bc8ca440129

![image](https://user-images.githubusercontent.com/898670/69203244-6f693b00-0b09-11ea-82de-233d5fa01e25.png)
