### ISSUE TITLE
[enhancement] please add suport for a "hint" span

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#2]
Can you add an option to define an hint to each form element. This hint should be append to element as an span element an formatted by css.

Like this:

`<label for="website">Website:</label>
            <input type="url" name="website" placeholder="http://example.com" required pattern="(http|https)://.+"/>
            <span class="form_hint">Proper format "http://example.com"</span>`

**Comment by nicksagona** [comment]
Ok, hints for fields are now support much in the same way the labels behave. You can do something like this:

``` php
$website = new Element\Input\Url('website');
$website->setHint('Enter a URL');
$website->setHintAttribute('class', 'field-hint');
```

Also, hints are supported in field config arrays as well:

``` php
$fields = [
    'website' => [
        'type' => 'url',
        'hint' => 'Enter a URL',
        'hint-attributes' => [
            'class' => 'field-hint'
        ]
    ]
];

$form = new Pop\Form\Form($fields);
```

In either case, the HTML will render like this:

``` html
<input type="url" name="website" />
<span class="field-hint">Enter a URL</span>
```

Let me know if that's working for you. Thanks.

**Comment by B0bbyD0llar** [comment]
Hi, big thx for this fast support. I use a teamplate, so i have to add `[{website_hint}]` to my form. May you can update the readme. So the other users can understand this nice feature.

By the way. How can i positing the error message in a template? `[{website_error}]` doesnt work.

**Comment by nicksagona** [comment]
Sure I'll look to add to the README. I'm acutally working on the docs currently. Prob about 85% complete at: http://docs.popphp.org/en/latest/

As soon as the docs are finished, I'll be pushing live with a website with a link to them, etc.

As for your question about errors - errors are automatically appended (or prepended) to the element when you return to output the form that has failed validation. So you don't have put anything in the template, it'll automatically display like this:

``` html
            <tr>
                <td>
                    <label for="username">Username:</label>
                </td>
                <td>
                    <input type="text" name="username" id="username" value="dfv&*(^*.." required="required" size="40" />
<div class="error">The value must only contain alphanumeric characters.</div>
                </td>
            </tr>
```

That's the default setting for error display. There is a measure of control over how and where the errors display with the form elements. You can call the "setErrorDisplay($container, array $attribs, $pre = false)" method on the form object:

``` php
$form->setErrorDisplay('span', ['class' => 'field-error'], true);
```

The "$pre" parameter will set it to prepend the errors before the form element on rendering the form.

Let me know if that helps. Thanks.
