### ISSUE TITLE
[Bug] Checkbox is wrongly checked

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#23]
Hello,
i have a simple checkbox like that:
```php
$form = new Form();
$cb1 = new Checkbox('test1','test1');
$cb2 = new Checkbox('test2','test2');
$cb3 = new Checkbox('test3','test3');
$form->addFields([$cb1,$cb2,$cb3]);

$submit = new Button('submit', 'save');
$submit->setAttribute('class', 'btn btn-primary');
$form->addField($submit);

if ($_POST) {
      $form->setFieldValues($_POST);
      // ... do something to process form data
}
```
this works fine so far.

Now when I submit the form without checking the checkbox and the form is redisplayed due to an incorrect entry, all the checkboxes are checked.
This does not happen when I use a checkbox set.

**Comment by nicksagona** [comment]
Thanks - this bug has been patch in 3.6.1
