### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#24]
Hello,

are there plans to support PHP 8.1?

i have some trouble with:

Return type of Pop\Form\Form::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

File: [.../vendor/popphp/pop-form/src/FormTrait.php:97]

**Comment by B0bbyD0llar** [comment]
there are some more:

- PHP Deprecated: Return type of Pop\Form\Form::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/FormTrait.php:97
- PHP Deprecated: Return type of Pop\Form\Form::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/FormTrait.php:108
- PHP Deprecated: Return type of Pop\Form\Form::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/FormTrait.php:120
- PHP Deprecated: Return type of Pop\Form\Form::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/FormTrait.php:131
- PHP Deprecated: Return type of Pop\Form\Form::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Form.php:526
- PHP Deprecated: Return type of Pop\Form\Form::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/FormTrait.php:53
- PHP Deprecated: Return type of Pop\Form\Fieldset::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:726
- PHP Deprecated: Return type of Pop\Form\Fieldset::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:737
- PHP Deprecated: Return type of Pop\Form\Fieldset::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:749
- PHP Deprecated: Return type of Pop\Form\Fieldset::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:760
- PHP Deprecated: Return type of Pop\Form\Fieldset::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:214
- PHP Deprecated: Return type of Pop\Form\Fieldset::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/popphp/pop-form/src/Fieldset.php:408

**Comment by nicksagona** [comment]
Ok - I've finished going through the entire framework to add support for PHP 8.1. Please pull down the latest version of the framework or this repo. The issues should be patched. Thanks for your continued support of Pop PHP.

**Comment by B0bbyD0llar** [comment]
Hello Nick,
thank you very much. Thank you for doing all the work!
