### ISSUE TITLE
No way to render all fieldsets

### ISSUE THREAD

**Issue by XedinUnknown** [popphp/pop-form#26]
Hi!

## Scenario
A form is being configured somewhere, like in a DI container. Then, a view tries to render it, knowing that it has a `$form` variable of type `Pop\Form\Form`. The view, being a useful separation of presentation logic, cannot know how many fields the form has been configured with, although it can know (from the `pop-form` architecture, since it depends on the concrete class `Form`) that if there are any fields at all, then they belong to a fieldset. All fields belong to a fieldset. The view does not know how many fieldsets there are, but it just needs to output all of them, however many there are, and their fields.

## Problem
The `Form` class does not expose its fieldsets. You can `getFieldset()` to get the "current" fielset. You can `setCurrent()` to set the index of the current fielset. But for that, you have to know how many fielsets there are, and potentially even their significance. But that's not the job of the view; the view simply decides _how_ to render any fielsets there may be, and their fields. If you knew at least the number of fielsets in the form, you could `for ($i=0; $i < $fieldsetsCount; $i++)`, but there's no way to know even that: `Form#count()` counts the total number of fields in all fielsets, but not the number of fielsets. `Form#getIterator()` returns a list of all _fields_ of a form from all of its fieldsets, but without knowledge of the fieldsets themselves.

In conclusion, there's no way to get all fieldsets, not even their amount, and therefore there's no way to render the whole form including any and all of its fielsets and their fields - without coupling the rendering logic to the knowledge of form configuration, which happens elsewhere, perhaps in a different module, and therefore cannot be known.

IMHO, the whole point of having a form library like this is to separate form configuration from its consumption (validation, value retrieval, rendering, etc), and the inability to enumerate fieldsets defeats that point (unless you are guaranteed to only ever have 1 fieldset in your form).

## Suggested Solution
Add `Form::getFieldsets(): iterable<Fieldset>`. Then, presentation (and any other) logic could iterate over each `Fieldset`, and over each field of that fieldset (retrieved via `Fieldset#getAllFields())`, to render the whole form with fieldsets - regardless of how the form and the fieldsets are configured.

**Comment by nicksagona** [comment]
Wow - yea thanks for the catch on that. That is a complete oversight on my part. In almost every situation with a class with an iterable collection I usually have a "get" method to get (and iterate) over that collection - but it wasn't included it on the form class. I just added a `getFieldsets()` method and a `hasFieldsets()` method and it's available in the new release I just pushed out - 3.6.6.

**Comment by XedinUnknown** [comment]
Oh wow! - thanks for the quick response and update! Stellar!
