### ISSUE TITLE
Attribute Transformation

### ISSUE THREAD

**Issue by XedinUnknown** [popphp/pop-form#27]
There are cases where I'd like the actual attibute name to be rendered differently than its raw value - without changing that raw value. For example, you may want to encode the value for a specific purpose, escape something in it, or render it differently in the HTML. For some implementations, such transformations are inherent to their purpose. In my case, it's the following.

My form fields correspond to setting keys, as it is very convenient to operate on them this way. Some settings (in the future, I hope all) are namespaced, e.g. a key may be `my_key`, or it could be `my_module/my_key`, or even `my_module/some_section/my_key`. When it comes to rendering this in the browser and handling it in a form submission request, there are certain implications, however:

1. There are restrictions on what makes a legal `name` attribute value for an HTML element. Different sources claim different rules, but the official source says that any legal attribute value is a legal name. So, it should be possible to use e.g. `/` in a field's `name`, but that's not 100%. `.` seems to be fine, though, e.g. `my_module.my_key`.
2. Symbols like `/` and `.` get transformed to `_` by PHP. If I send a field called `my_module/my_key`, the `$_POST` superglobal will contain the key `my_module_my_key`. This appears to suggest that keys namespaced in such a way cannot be resolved, because they are indistinguishable from non-namespaced names, as the delimiter information is erased.

The only sane way of achieving namespacing (this is very handy if you have a truly modular application, which is IMHO the point of having a forms lib) is by using nested values. The field `name` attributes would need to contain names like `my_module[my_key]`, which gets transformed by PHP into `$_POST['my_module'][''my_key']`. This is a common approach when using an unknown number of fields (let's say, the user can add unlimited addresses: `user_address[][street1]`), or to group some values (perhaps, they need to gets saved together, no matter how many there are). This is the approach that I went with, but simply for the sake of namespacing: values in each distinct key (FQN of sorts) are saved separately under that key.

To do this, I need some way of saying:

> For any input, I want to transform the field name e.g. `one/two/three` into `one[two][three]` when rendering that attribute. I still want to refer to the field by its original name `one/two/three`, as I will set/read/validate that field based on that name - the name I have given it at initialization. I just want to render it in this way for HTML output.

As far as I know, currently there's no way of doing that. There's already a seeming inconsistency, because an element has both a `getName()`, and an attribute called `name`, and these two are used differently. So, my suggestion of only modifying the attribute (not the `getName()`) doesn't seem to break anything.

The best way that I can think of is adding a generic "filter" for all attributes. For example, before rendering any attribute value, the `AbstractElement` (or another element ancestor) could retrieve it via another method, e.g. `$value = $this->getAttributeValue(string $attributeName): scalar`. Just this simple change would allow me to override the `getAttributeValue()` method in any descendant, and do my transformation there at the time of rendering - without changing the actual value of the attribute, as recorded.

In fact, there's already a [`getAttribute()`](https://github.com/popphp/pop-dom/blob/master/src/Child.php#L391) method on `Child`. The problem is that it is not used [in `render()`](https://github.com/popphp/pop-dom/blob/master/src/Child.php#L475): that just iterates over the `$attributes` property. If it used `getAttributes()`, there would be a way to override that and filter the `name` value as part of the whole set, but it isn't. If I used it, though, I'd try to make sure there's consistency for every way of getting an attribute's value: whether getting a single attribute's value, or a map with all attributes. I would leave the `getName()` not connected to the attribute, and use it to refer to a field in the scope of a form, like for populating, reading, and validating values.

**Comment by nicksagona** [comment]
Ok so trying to get to the root of what you're asking for. Are you saying that if over in the `pop-dom` component `Pop\Dom\Child` class `render()` method - if this code:
```php
        // Format child attributes, if applicable.
        if (count($this->attributes) > 0) {
            foreach ($this->attributes as $key => $value) {
                $attribAry[] = $key . "=\"" . $value . "\"";
            }
            $attribs = ' ' . implode(' ', $attribAry);
        }
```
changed to something like this:
```php
        // Format child attributes, if applicable.
        if ($this->hasAttributes()) {
            $attributes = $this->getAttributes();
            foreach ($attributes as $key => $value) {
                $attribAry[] = $key . "=\"" . $value . "\"";
            }
            $attribs = ' ' . implode(' ', $attribAry);
        }
```
You could override the `getAttributes()` method and accomplish what you're trying to accomplish?

**Comment by nicksagona** [comment]
Closing this issue out. The suggested change has been made to pop-dom.

**Comment by XedinUnknown** [comment]
Seems it's done in https://github.com/popphp/pop-dom/commit/36c4ed283c1189c6266bcdc7c8dceeaba6f7ece1. Should work, thank you! 🙏
