### ISSUE TITLE
replace default error message

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#29]
Hi,

if a form field is marked as “required”, the error message “This field is required” is displayed. Can this message be changed/localized? At best globally?

**Comment by nicksagona** [comment]
Yes, that's something that probably needed to happen a long time ago and was never addressed. That message needs to be positioned in a way that's easy to set up for I18N messaging or other overriding reasons.

Check out the code that was just pushed up to the v4-dev branch. There's a new `$requiredMessage` property for the AbstractElement class that defaults to “This field is required”, but can be overridden by a new second parameter in the method:

```php
setRequired(bool $required, ?string $requiredMessage = 'This field is required.')
```

Also when using the form field config way of doing things, the new parameter `require_message` is now supported:

```php
$fields = [
    [
        'username' => [
            'type'             => 'text',
            'label'            => 'Username:',
            'required'         => true,
            'required_message' => 'Hey! The username field is required!',
        ],
        'file' => [
            'type'  => 'file',
            'label' => 'File:'
        ]
    ],
    [
        'submit' => [
            'type'  => 'submit',
            'value' => 'SUBMIT'

        ]
    ]
]
```

**Comment by nicksagona** [comment]
I'm going to go ahead and close this out and merge this functionality.

**Comment by B0bbyD0llar** [comment]
Hi Nick,
thanks for this great improvement!
