### ISSUE TITLE
[enhancement] please add input type "date"

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#3]
please add the html5 input type date.
thx

**Comment by nicksagona** [comment]
Hey, ok, I've added support for all of the rest of the HTML5 field types. The reason they weren't originally included was that originally, browser support was not consistent with some of them. Today support is somewhat better (yet still not fully supported across all browsers for some of the field types.) So, they are now all available, it'll just be up to the developer to handle degrading the field down if the field type not supported by the user's browser. Let me know if it's working for you. Thanks.
