### ISSUE TITLE
[question] password validate

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#5]
Hi, can i use the validator to check if the password and password_confirmation match?

**Comment by nicksagona** [comment]
B/c things like matching passwords requires there to be values present, one way to handle it is in your form object, extend the "setFieldValues(array $values = null)" method and add the validator "on-the-fly" like this:

``` php
<?php

namespace MyApp\Form;

use Pop\Validator;

class Member extends \Pop\Form\Form
{

    public function setFieldValues(array $values = null)
    {
        parent::setFieldValues($values);

        if (($_POST) && (null !== $this->password1)) {
            if ($this->password1 != $this->password2) {
                $this->getElement('password2')
                     ->addValidator(new Validator\Equal($this->password1, 'The passwords do not match.'));
            }
        }
    }
}
```

So when you trigger the validation sequence like this:

``` php
if ($_POST) {
    $form->setFieldValues($_POST);
    if (!$form->isValid()) {
        // Fails
    } else {
        // Passes
    }
}
```

The new validator will be there and trigger an error if the two password values are not equal.

Let me know if that helps. Thanks.

**Comment by nicksagona** [comment]
This is actually something I've been thinking about... possibly added a simple "match" validation to trigger a check between two fields. The above example is more for the situation where field values may or may not be there, or may or may not be changing (like an existing member updating their profile, but not changing their password, etc.)

**Comment by nicksagona** [comment]
Ok I just added support to add a validator with the value being the field name you want to check against. It'll look for that special situation and validate a match between the fields, like this:

``` php
$fields = [
    'username' => [
        'type'     => 'text',
        'label'    => 'Username',
        'required' => true
    ],
    'password1' => [
        'type'     => 'password',
        'label'    => 'Password',
        'required' => true
    ],
    'password2' => [
        'type'       => 'password',
        'label'      => 'Re-Type Password',
        'required' => true,
        'validators' => new Validator\Equal('password1', 'The passwords do not match.')
    ],
    'submit' => [
        'type'       => 'submit',
        'value'      => 'SUBMIT',
        'attributes' => [
            'class'  => 'submit-btn'
        ]
    ]
];
```

Update your version and see if that works for you. Thanks.

**Comment by B0bbyD0llar** [comment]
Thx. This works great,
