### ISSUE TITLE
[featurerequest] Enhancement to datalist input element

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#6]
Hi,

please extend the datalist input element similar to the select field. 

normal select looks like this:

``` html
<select name="example" id="example" required="required">
         <option value="first">This is the first entry</option>
         <option value="second">This is the second entry</option>
     </select>
```

So you have different values for sumbit and for display.

the normal datalist looks like this:

``` html
<input type="text" name="example" id="example" value="" list="example_datalist" placeholder="give me something..." size="60" required="required" />
<datalist id="example_datalist">
    <option value="first" />
    <option value="second" />
</datalist>
```

![image](https://cloud.githubusercontent.com/assets/14181646/14180191/45d89a92-f762-11e5-9493-717fed91bd04.png)

it would be great if the datalist look like this

``` html
<input type="text" name="example" id="example" value="" list="example_datalist" placeholder="give me something..." size="60" required="required" />
<datalist id="example_datalist">
    <option value="first">This is the first entry</option>
    <option value="second" >This is the second entry</option>
</datalist>
```

![image](https://cloud.githubusercontent.com/assets/14181646/14180201/50b04578-f762-11e5-987a-94bae6984622.png)

i have tested on latest Chrome, latest Firefox and IE11. It works like a charm.

I hope you know what I mean. thanks in advance.

My example html-file: [test.html.txt](https://github.com/popphp/pop-form/files/197916/test.html.txt)

**Comment by nicksagona** [comment]
Ok I've added the ability to use an associative array to have a better descriptive text for datalists like requested. Pull down the lasted patch and let me know if it works for you. Here's a quick example:

``` php
$search = new Input\Datalist('search', [
    'red'   => 'The color red',
    'green' => 'The color green',
    'blue'  => 'The color blue'
]);
```

**Comment by B0bbyD0llar** [comment]
It works fine. Thanks.

**Comment by B0bbyD0llar** [comment]
after few tests i have a small problem. If the array key have only numbers it will not work. I have tried to set a simple typecast like this:

``` php
$result=$db->query("SELECT kstNummer,kstName FROM kst");
while ($data = $result->fetch(PDO::FETCH_NUM)) {
  $valuesKST[ (string) $data[0] ] = $data[0]." (".$data[1].")";
}                               
$kst= new Input\Datalist("kst",$valuesKST);
```

but the array key is still an integer while there is no alphanumeric char in the key.

i have no idea how can i solve this problem. may it is useful add an optional parameter to the datalist element.

Any idea?

**Comment by nicksagona** [comment]
How about we just force it to use the key/value pair at all times? Basically like the select element does. I really think that may the only way to do it. Browsers that support the text hint value will display it, those that don't will just ignore it.

**Comment by nicksagona** [comment]
Ok check out the latest patch. Let me know if that works for you. Thanks.

**Comment by B0bbyD0llar** [comment]
I think the same. In my case i will use always this way.
Thx, now it works fine.
