### ISSUE TITLE
[bug] set a value to an textarea

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#7]
If i set a value to a textarea field it will not work.

**Comment by B0bbyD0llar** [comment]
also if i set an value to an select element.

**Comment by B0bbyD0llar** [comment]
or an Date element.

**Comment by nicksagona** [comment]
Ok these have been fixed. They should work now, check them out.

FYI, it's the setValue() method for Textarea and setMarked() method for Select, CheckboxSet and RadioSet.

Thanks

**Comment by B0bbyD0llar** [comment]
it works. Thanks. 

Ahhhhhhh *_facepalm_ of course thats it. Thanks again.

**Comment by nicksagona** [comment]
No prob - thanks for the contributions. Let me know if you find anything else.
