### ISSUE TITLE
[bug] After update from 2.2.3 to 3.0.2 i get this error

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#8]
i update via composer by simply change the version number.

```
Error
Call to undefined method Pop\Form\Form::addElements() 
```

if i go back to old version, the same code works fine.

**Comment by nicksagona** [comment]
Hey, so, with v3 being a major version release, as one might expect, there was a fairly significant refactor/restructure to parts of the component with some of it breaking BC. I had been meaning to write up a proper changelog, but haven't had the chance yet. I also just realized I didn't correctly update the README file to reflect the changes in the examples there.

In the case of the method you'd asking about, `addElements` and also `addElement` have simply been changed to `addFields` and `addField`, respectively.

The component was refactored to group things a little more syntactically correct in HTML with support for handling/managing fieldsets with fields inside of them (formly referred to as "groups").

The documentation and API docs are correct though. You can check them out here and look over what's changed:

- http://docs.popphp.org/en/latest/user_guide/forms.html
- http://api.popphp.org/3.6/namespaces/Pop.Form.html

And if you use an IDE with code completion, it should tip you off to where the broken issues are when using the newer version.

In the meantime, I'll make the edits to the README and add a CHANGELOG file too.

**Comment by nicksagona** [comment]
Ok just updated the README file and added a CHANGELOG file. I pushed it out in v3.0.3. Let me know if this helps clear things up. Thanks.
