### ISSUE TITLE
[Enhancement] add method setDisabled()

### ISSUE THREAD

**Issue by B0bbyD0llar** [popphp/pop-form#9]
May you can add a new method setDisabled() to your abstract element. similar to setRequired().

Currently i use an workaround:

`->setAttribute('disabled')`

but this is not really clean solution, the setAttribute normally expects a second parameter.

**Comment by nicksagona** [comment]
That's a good idea, and I'll do one better. I've actually been using the whole "disabled" and "readonly" attributes in some applications I've been working on lately. So I've added setDisabled() and setReadonly() as methods to the abstract element class. It's been released in v3.1.0 - let me know if it works for you. Thanks.

**Comment by B0bbyD0llar** [comment]
I will try. First i have migrate my project to pop-form 3.x ;-)
